<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="platoon" nsURI="http://www.example.org/platoon" nsPrefix="platoon">
  <eClassifiers xsi:type="ecore:EClass" name="Platoon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leader" lowerBound="1"
        eType="#//PlatoonLeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="follower" lowerBound="1"
        upperBound="-1" eType="#//PlatoonFollower" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="follows" eType="#//Platoon"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinplatoonCord" eType="#//JoinPlatoonCoord"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desiredGapSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatoonFollower" eSuperTypes="#//PlatoonVehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinCoord" eType="#//JoinPlatoonCoord"
        eOpposite="#//JoinPlatoonCoord/follower"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marks" eType="#//JoiningPosition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatoonLeader" eSuperTypes="#//PlatoonVehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joiningRequest" eType="#//JoiningVehicle"
        eOpposite="#//JoiningVehicle/wantsToJoin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinCoord" eType="#//JoinPlatoonCoord"
        eOpposite="#//JoinPlatoonCoord/leader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isAwareOf" eType="#//PlatoonFollower"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="follows" eType="#//Vehicle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinPlatoonCoord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leader" lowerBound="1"
        eType="#//PlatoonLeader" eOpposite="#//PlatoonLeader/joinCoord"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="follower" lowerBound="1"
        eType="#//PlatoonFollower" eOpposite="#//PlatoonFollower/joinCoord"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joiningvehicle" lowerBound="1"
        eType="#//JoiningVehicle" eOpposite="#//JoiningVehicle/joinCoord"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoiningVehicle" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertsIn" eType="#//FrontGap"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wantsToJoin" eType="#//PlatoonLeader"
        eOpposite="#//PlatoonLeader/joiningRequest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinCoord" eType="#//JoinPlatoonCoord"
        eOpposite="#//JoinPlatoonCoord/joiningvehicle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locatedIn" eType="#//JoiningPosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrontGap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualGapSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatoonVehicle" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forms" eType="#//FrontGap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatooningSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platoon" upperBound="-1"
        eType="#//Platoon" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoiningPosition"/>
</ecore:EPackage>
